#!/bin/sh
#  
numargs=$#
this_script=$0
username=$1
BASE_DIR=~/openmining_project
QMAKE=/usr/local/Qt-5.4.0/bin/qmake


# qt3d
########################################################################################################
#./setup_qt3d $username
cd $BASE_DIR
sudo -u $username git clone git://gitorious.org/qt/qt3d.git 
if [ "$?" -ne 0 ]; then
  exit $?
fi

echo $PATH
cd $BASE_DIR/qt3d
#patch -N src/threed/painting/qglpainter.cpp < ../openmining/third_party_patches/patch.qglpainter.cpp
sudo -u $username QMAKE
if [ "$?" -ne 0 ]; then
  exit $?
fi

sudo -u $username make
if [ "$?" -ne 0 ]; then
  exit $?
fi

make install
if [ "$?" -ne 0 ]; then
  exit $?
fi

 

