#!/bin/sh
# don't start this script as root, run as a normal user. We need to run some actions as $USER, and others as root.
#  
numargs=$#
this_script=$0
username=$1
BASE_DIR=~/openmining_project
QMAKE=/usr/local/Qt-5.4.0/bin/qmake

echo "numargs = $numargs"

if [ "$numargs" = 0 ]; then
  username=$USER
  echo "re-running script as root..."
  sudo ./$this_script $USER # re-run this script as root, passing in the username of the original caller
  echo "finished running as root."
  exit $?
fi

echo "username = $username"
. ./setup_path
sudo -u $username echo $PATH

required_packages="build-essential perl python git "^libxcb.*" libx11-xcb-dev libglu1-mesa-dev libxrender-dev flex bison gperf libicu-dev libxslt-dev ruby libasound2-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev libpq5 libpq-dev libboost-serialization1.48 postgresql-client-9.1"
optional_packages="synaptic cscope openssh-server"
sudo apt-get install -y $required_packages $optional_packages
# optional extras
if [ "$?" -ne 0 ]; then
  exit $?
fi

sudo -u $username mkdir -p $BASE_DIR
cd $BASE_DIR


# qt5
########################################################################################################
#./setup_qt5 $username

# qt3d
########################################################################################################
#./setup_qt3d $username

# qwtplot3d
########################################################################################################
#./setup_qwtplot3d $username

cd $BASE_DIR/openmining
sudo -u $username $QMAKE
if [ "$?" -ne 0 ]; then
  exit $?
fi
sudo -u $username make
if [ "$?" -ne 0 ]; then
  exit $?
fi
cd $BASE_DIR
